#!/bin/bash

# copy this file to ./lib/cfg.sh and make changes

# types of cfgs you wish to generate
# used along with system_cfgs below
readonly -a cfg_types=(
	"input_player1_turbo_btn"
	"input_player2_turbo_btn"
	"input_turbo_default_button"
)

# system_cfgs: the system cfgs you wish to generate
# of the form <machine>_<system>_<cfg_type>="value"
# used along with cfg_types above
readonly a500_amstradcpc_input_player1_turbo_btn="x"
readonly a500_amstradcpc_input_turbo_default_button="a"
readonly a500_atari5200_input_turbo_default_button="a"
readonly a500_atarijaguar_input_player1_turbo_btn="x"
readonly a500_moto_input_player1_turbo_btn="x"
readonly a500_msx_input_turbo_default_button="a"
readonly a500_sg_1000_input_turbo_default_button="a"
readonly a500_videopac_input_player1_turbo_btn="x"

readonly psclassic_amstradcpc_input_player1_turbo_btn="x"
readonly psclassic_amstradcpc_input_turbo_default_button="a"
readonly psclassic_atari5200_input_turbo_default_button="a"
readonly psclassic_atarijaguar_input_player1_turbo_btn="x"
readonly psclassic_moto_input_player1_turbo_btn="x"
readonly psclassic_msx_input_turbo_default_button="a"
readonly psclassic_sg_1000_input_turbo_default_button="a"
readonly psclassic_videopac_input_player1_turbo_btn="x"

readonly retrobar_amstradcpc_input_player1_turbo_btn="x"
readonly retrobar_amstradcpc_input_turbo_default_button="a"
readonly retrobar_atari5200_input_turbo_default_button="a"
readonly retrobar_atarijaguar_input_player1_turbo_btn="x"
readonly retrobar_moto_input_player1_turbo_btn="x"
readonly retrobar_msx_input_turbo_default_button="a"
readonly retrobar_sg_1000_input_turbo_default_button="a"
readonly retrobar_videopac_input_player1_turbo_btn="x"

readonly retrobed_amstradcpc_input_player1_turbo_btn="x"
readonly retrobed_amstradcpc_input_turbo_default_button="a"
readonly retrobed_atari5200_input_turbo_default_button="a"
readonly retrobed_atarijaguar_input_player1_turbo_btn="x"
readonly retrobed_moto_input_player1_turbo_btn="x"
readonly retrobed_msx_input_turbo_default_button="a"
readonly retrobed_sg_1000_input_turbo_default_button="a"
readonly retrobed_videopac_input_player1_turbo_btn="x"

readonly retroboy_amstradcpc_input_player1_turbo_btn="x"
readonly retroboy_amstradcpc_input_turbo_default_button="a"
readonly retroboy_atari5200_input_turbo_default_button="a"
readonly retroboy_atarijaguar_input_player1_turbo_btn="x"
readonly retroboy_moto_input_player1_turbo_btn="x"
readonly retroboy_msx_input_turbo_default_button="a"
readonly retroboy_sg_1000_input_turbo_default_button="a"
readonly retroboy_videopac_input_player1_turbo_btn="x"

readonly segamini_amstradcpc_input_player1_turbo_btn="x"
readonly segamini_amstradcpc_input_turbo_default_button="a"
readonly segamini_atari5200_input_turbo_default_button="a"
readonly segamini_atarijaguar_input_player1_turbo_btn="x"
readonly segamini_gx4000_input_player1_turbo_btn="x"
readonly segamini_gx4000_input_turbo_default_button="a"
readonly segamini_moto_input_player1_turbo_btn="x"
readonly segamini_msx_input_turbo_default_button="a"
readonly segamini_sg_1000_input_turbo_default_button="a"
readonly segamini_videopac_input_player1_turbo_btn="x"

# systmes that will have input_player1_turbo_btn and input_player2_turbo_btn both set to y
readonly -a y_turbo_systems=(
	"amiga"
	"atari2600"
	"atari5200"
	"atari7800"
	"atarilynx"
	"c64"
	"coleco"
	"gamegear"
	"gb"
	"gbc"
	"intellivision"
	"mastersystem"
	"msx"
	"ngpc"
	"pcfx"
	"sg-1000"
	"vic20"
	"x1"
	"x68000"
	"zxspectrum"
)

# input values per system and button
readonly -A input_btn_values=(
	["a500;a"]="1"
	["a500;b"]="2"
	["a500;x"]="0"
	["a500;y"]="3"
	["a500;m"]="99"

	["psclassic;a"]="1"
	["psclassic;b"]="2"
	["psclassic;x"]="0"
	["psclassic;y"]="3"
	["psclassic;m"]="99"

	["retrobar;a"]="5"
	["retrobar;b"]="4"
	["retrobar;x"]="1"
	["retrobar;y"]="3"
	["retrobar;m"]="99"

	["retrobed;a"]="4"
	["retrobed;b"]="2"
	["retrobed;x"]="3"
	["retrobed;y"]="1"
	["retrobed;m"]="99"

	["retroboy;a"]="0"
	["retroboy;b"]="1"
	["retroboy;x"]="2"
	["retroboy;y"]="3"
	["retroboy;m"]="99"

	["retrovlieg;a"]="1"
	["retrovlieg;b"]="2"
	["retrovlieg;x"]="7"
	["retrovlieg;y"]="6"
	["retrovlieg;m"]="99"

	["segamini;a"]="4"
	["segamini;b"]="2"
	["segamini;x"]="3"
	["segamini;y"]="1"
	["segamini;m"]="99"
)

# roms that will have input_player1_turbo_btn and input_player2_turbo_btn both set to y
readonly -a y_turbo_rom_cfgs=(
	"arcade;1942"
	"arcade;1943"
	"arcade;ddux"
	"arcade;digdug"
	"arcade;esb"
	"arcade;fantzn2x"
	"arcade;galaga"
	"arcade;galaxian"
	"arcade;gaplus"
	"arcade;invaders"
	"arcade;junofrst"
	"arcade;mooncrst"
	"arcade;mpatrol"
	"arcade;pooyan"
	"arcade;raiden"
	"arcade;rygar"
	"arcade;shollow"
	"arcade;stargate"
	"arcade;starwars"
	"arcade;tempest"
	"arcade;terracre"
	"arcade;timeplt"
	"arcade;vsduckhunt"
	"arcade;aliensyn"
	"mame2003-plus;astrof"
	"arcade;blktiger"
	"mame2003-plus;bublbobr"
	"arcade;contra"
	"arcade;darius"
	"arcade;gigawing"
	"arcade;imgfight"
	"arcade;nbbatman"
	"arcade;p47"
	"arcade;rampage"
	"arcade;robocop"
	"arcade;rtype"
	"arcade;rtypeleo"
	"arcade;salmndr2"
	"arcade;scontra"
	"mame2003-plus;shienryu"
	"arcade;simpsons2pj"
	"arcade;ssridersubc"
	"arcade;tmnt22pu"
	"arcade;tmnt2pj"
	"arcade;wb3"
	"arcade;xexex"
	"mame2010;ncv1"
	"mame2010;ncv2"
	"neogeo;androdun"
	"neogeo;blazstar"
	"neogeo;lresort"
	"neogeo;maglord"
	"neogeo;preisle2"
	"neogeo;pulstar"
	"neogeo;s1945p"
	"neogeo;sonicwi2"
	"neogeo;sonicwi3"
	"pc;JAZZ"
	"pc;NUKEM2"
	"arcade;batsugun"
	"arcade;ddonpach"
	"arcade;dogyuun"
	"arcade;donpachi"
	"arcade;feversos"
	"arcade;fireshrk"
	"arcade;gunbird"
	"arcade;gunbird2"
	"arcade;guwange"
	"arcade;kingdmgp"
	"arcade;progear"
	"arcade;s1945"
	"arcade;s1945ii"
	"arcade;samuraia"
	"arcade;sstriker"
	"arcade;twincobr"
	"arcade;vimana"
	"arcade;zerowing"
)

# rom-specific cfgs
readonly -A rom_cfgs=(
	["amiga;Battle Squadron : The Destruction of the Barrax Em (v1.7 0941);input_turbo_default_button"]="a"
	["atari7800;Astro Blaster (20230627) (FB86A5A0);input_turbo_default_button"]="a"
	["atari7800;Bentley Bear - Crystal Quest by Bob DeCrescenzo (V20130718RC5);input_turbo_default_button"]="a"
	["arcade;astorm;input_player1_turbo_btn"]="x"
	["arcade;dmnfrnt;input_player1_turbo_btn"]="x"
	["arcade;shollow;input_turbo_default_button"]="a"
	["intellivision;d2k;input_turbo_default_button"]="a"
	["intellivision;Princess Quest;input_turbo_default_button"]="a"
	["intellivision;Space Patrol - Full Cartridge Release - 2007;input_turbo_default_button"]="a"
	["mame2003-plus;asteroid;input_player1_turbo_btn"]="x"
	["mame2003-plus;bucky;input_player1_turbo_btn"]="x"
	["mame2003-plus;p47;input_turbo_default_button"]="a"
	["mame2003-plus;seganinj;input_player1_turbo_btn"]="x"
	["mame2010;ncv1;input_turbo_default_button"]="a"
	["mame2010;ncv2;input_turbo_default_button"]="a"
	["megadrive;Space Harrier II (World);input_player1_turbo_btn"]="x"
	["neogeo;lasthope;input_player1_turbo_btn"]="x"
	["neogeo;mslug;input_player1_turbo_btn"]="x"
	["neogeo;mslug3;input_player1_turbo_btn"]="x"
	["neogeo;mslug4;input_player1_turbo_btn"]="x"
	["neogeo;mslug5;input_player1_turbo_btn"]="x"
	["neogeo;mslugx;input_player1_turbo_btn"]="x"
	["neogeo;shocktr2;input_player1_turbo_btn"]="x"
	["neogeo;spinmast;input_player1_turbo_btn"]="x"
	["pc;HOCUS;input_player1_turbo_btn"]="x"
	["pc;HOCUS;input_turbo_default_button"]="a"
	["pc;JAZZ;input_turbo_default_button"]="a"
	["pc88;Gradius;input_player1_turbo_btn"]="y"
	["pc88;Gradius;input_turbo_default_button"]="a"
	["pc88;Melt Down;input_player1_turbo_btn"]="x"
	["pc88;Melt Down;input_turbo_default_button"]="y"
	["quake;dopa;input_player1_turbo_btn"]="m"
	["quake;hipnotic;input_player1_turbo_btn"]="m"
	["quake;id1;input_player1_turbo_btn"]="m"
	["quake;rogue;input_player1_turbo_btn"]="m"
	["sg-1000;Knightmare (Taiwan) (Unl);input_turbo_default_button"]="b"
	["arcade;esprade;input_player1_turbo_btn"]="x"
	["arcade;mmatrix;input_player1_turbo_btn"]="x"
	["snes;U.N. Squadron (USA);input_player1_turbo_btn"]="a"
	["snes;U.N. Squadron (USA);input_turbo_default_button"]="y"	
	["snes-msu1;Contra (USA) (MSU1);input_player1_turbo_btn"]="y"
	["snes-msu1;Contra (USA) (MSU1);input_turbo_default_button"]="x"
	["x68000;Chourensha 68K v1.01 (1995)(Famibe No Yosshin);input_turbo_default_button"]="a"
	["x68000;Flame Wing v1.02 (1994)(Itasenpara);input_turbo_default_button"]="a"
	["x68000;Nemesis '90 Kai (1993)(SPS);input_turbo_default_button"]="a"
	["x68000;Nemesis '94 Gradius 2 (1994)(Gra2 Project Team);input_turbo_default_button"]="a"
	["zxspectrum;Flying Shark 128K (1987)(Firebird);input_turbo_default_button"]="a"
)
